### ISSUE TITLE
An article "Algebraic Effects and Handlers on Desk"

### ISSUE THREAD

**Issue by ryo33** [yallop/effects-bibliography#164]
https://github.com/Hihaheho/Desk/blob/main/docs/blog/0002-algebraic-effects.md
I've written this article about the effects of Desk-lang.
Although it's not academic but should be helpful to know what's algebraic effects in short and the characteristics of Desk-lang in the context of algebraic effects.
Is it appropriate for this repository?

I'd like to change the following

* **Desk**: A statically-typed functional language with effect system based on set-operation  
  by Ryo Hirayama from Hihaheho Studio  
  ([GitHub](https://github.com/Hihaheho/Desk))

to

* **Desk**: A true pure statically-typed functional language with an effect system based on set-operation  
  by Ryo Hirayama from Hihaheho Studio  
  ([GitHub](https://github.com/Hihaheho/Desk)) ([an effects tutorial article](https://github.com/Hihaheho/Desk/blob/main/docs/blog/0002-algebraic-effects.md))

The link name "an effects tutorial article" is ok?
The title of the article, "Algebraic Effects and Handlers on Desk" could be considered, but I feel it's not appropriate by being too long.

**Comment by yallop** [comment]
Yes, I think that the additional link to the tutorial (with the short name you propose) would be entirely appropriate for the repository.
