### ISSUE TITLE
Bibtex?

### ISSUE THREAD

**Issue by andrejbauer** [yallop/effects-bibliography#8]
It would probably be useful to have a Bibtex version of each paper. An easy solution would be to just add it to each entry.

**Comment by bobatkey** [comment]
A cheap and cheerful way of doing this would be to link to DBLP's record for each paper's bibtex. E.g., [http://dblp.uni-trier.de/rec/bibtex/journals/jfp/Atkey09]

**Comment by andrejbauer** [comment]
That's a good idea.

**Comment by yallop** [comment]
Linking to the DBLP record has worked well [elsewhere](https://github.com/metaocaml/metaocaml-bibliography).  Pull requests to update this repository similarly are welcome!

**Comment by dbuenzli** [comment]
For those doied papers there's also`doi2bib.org` for example https://doi2bib.org/bib/10.2307/1968337
which I think does the moral equivalent of:
```
> curl -LH "Accept: application/x-bibtex; charset=utf-8" https://doi.org/10.2307/1968337              
```
which sadly you can't get via query params.

**Comment by Tomatosoup97** [comment]
Hi! I have written a simple python script to automatically generate bibtex links for paper based on DBLP, it's available here: https://gist.github.com/Tomatosoup97/f6ae1b96e28e64c35d950967d51df3f2

And here is result of running it on current repo state: https://github.com/yallop/effects-bibliography/pull/103. One issue with the script which I didn't address yet, is that after we add support for doi (or other source), there would be two bibtex entries generated for papers with both DBLP and DOI link, but this can be resolved later.

I'm not sure whether we want to do anything with the script - it could be useful to generate links as we add more papers and/or validate in travis that each paper has a bibtex attached, when one is available.

**Comment by matijapretnar** [comment]
Are BibTeX links necessary if we already have DBLP links?

**Comment by yallop** [comment]
I think there's still some value in having direct BibTeX links (since not everything is in DBLP, for one thing).
